pub mod builder_gen;
pub mod companion_gen;
pub mod reader_gen;
pub mod schema_gen;
pub mod type_mapping;

use std::collections::HashMap;

use codegen_core::{escape_reserved_word, CodeWriter, Language};
use heck::ToSnakeCase;

use arrowc_schema::schema_def::ArrowSchemaDef;

/// Convert a field name to a valid Rust identifier (snake_case + keyword escape).
/// "user_id" → "user_id", "type" → "type_", "Type" → "type_"
pub fn rust_field_ident(name: &str) -> String {
    let snake = name.to_snake_case();
    escape_reserved_word(&snake, Language::Rust)
}

/// Generate a complete Rust source file for one Arrow schema definition.
/// The output includes all necessary imports, and the Schema/Builder/Reader types.
pub fn generate_rust_file(schema: &ArrowSchemaDef) -> String {
    let mut w = CodeWriter::new();

    // Collect companion structs
    let companion_list = companion_gen::collect_companions(schema);
    let companion_map: HashMap<String, companion_gen::CompanionInfo> =
        companion_list.into_iter().collect();

    // Imports
    generate_imports(&mut w, schema);
    w.blank();

    // Companion structs (before builder so they're in scope)
    companion_gen::generate_companions(&mut w, schema);

    // Schema
    schema_gen::generate_schema(&mut w, schema);
    w.blank();

    // Builder
    builder_gen::generate_builder(&mut w, schema, &companion_map);
    w.blank();

    // Reader
    reader_gen::generate_reader(&mut w, schema);

    w.finish()
}

fn generate_imports(w: &mut CodeWriter, schema: &ArrowSchemaDef) {
    w.line("// Generated by arrowc. Do not edit.");
    w.line("#![allow(clippy::too_many_arguments)]");
    w.blank();

    w.line("use std::sync::Arc;");
    w.blank();

    // Collect which arrow imports we need
    let mut needs_time_unit = false;
    let mut needs_fields = false;
    let mut needs_array_builder = false;

    for field in &schema.fields {
        check_imports(
            &field.arrow_type,
            &mut needs_time_unit,
            &mut needs_fields,
            &mut needs_array_builder,
        );
    }

    // arrow::datatypes
    let mut datatypes_imports = vec!["DataType", "Field", "Schema"];
    if needs_time_unit {
        datatypes_imports.push("TimeUnit");
    }
    if needs_fields {
        datatypes_imports.push("Fields");
    }
    w.line(&format!(
        "use arrow::datatypes::{{{}}};",
        datatypes_imports.join(", ")
    ));

    // arrow::array — collect needed types
    let mut array_imports: Vec<String> =
        vec!["ArrayRef".into(), "AsArray".into(), "RecordBatch".into()];

    if needs_array_builder {
        array_imports.push("ArrayBuilder".into());
    }

    for field in &schema.fields {
        collect_top_level_array_import(&field.arrow_type, &mut array_imports);
        collect_builder_imports(&field.arrow_type, &mut array_imports);
    }
    array_imports.sort();
    array_imports.dedup();

    w.line(&format!(
        "use arrow::array::{{{}}};",
        array_imports.join(", ")
    ));

    // arrow::error
    w.line("use arrow::error::ArrowError;");
}

fn check_imports(
    ty: &arrowc_schema::arrow_type::ArrowType,
    needs_time_unit: &mut bool,
    needs_fields: &mut bool,
    needs_array_builder: &mut bool,
) {
    use arrowc_schema::arrow_type::ArrowType;
    match ty {
        ArrowType::Timestamp { .. }
        | ArrowType::Time32 { .. }
        | ArrowType::Time64 { .. }
        | ArrowType::Duration { .. } => {
            *needs_time_unit = true;
        }
        ArrowType::Struct { fields } => {
            *needs_fields = true;
            *needs_array_builder = true;
            for f in fields {
                check_imports(
                    &f.arrow_type,
                    needs_time_unit,
                    needs_fields,
                    needs_array_builder,
                );
            }
        }
        ArrowType::Map { key, value, .. } => {
            *needs_fields = true;
            check_imports(
                &key.arrow_type,
                needs_time_unit,
                needs_fields,
                needs_array_builder,
            );
            check_imports(
                &value.arrow_type,
                needs_time_unit,
                needs_fields,
                needs_array_builder,
            );
        }
        ArrowType::List { element }
        | ArrowType::LargeList { element }
        | ArrowType::FixedSizeList { element, .. } => {
            check_imports(
                &element.arrow_type,
                needs_time_unit,
                needs_fields,
                needs_array_builder,
            );
        }
        _ => {}
    }
}

fn collect_top_level_array_import(
    ty: &arrowc_schema::arrow_type::ArrowType,
    imports: &mut Vec<String>,
) {
    use arrowc_schema::arrow_type::ArrowType;
    match ty {
        ArrowType::List { .. } | ArrowType::LargeList { .. } | ArrowType::FixedSizeList { .. } => {
            imports.push("ListArray".into());
        }
        ArrowType::Struct { .. } => {
            imports.push("StructArray".into());
        }
        _ => {
            let info = type_mapping::rust_type_info(ty);
            imports.push(info.array_type);
        }
    }
}

fn collect_builder_imports(ty: &arrowc_schema::arrow_type::ArrowType, imports: &mut Vec<String>) {
    use arrowc_schema::arrow_type::ArrowType;
    match ty {
        ArrowType::List { element }
        | ArrowType::LargeList { element }
        | ArrowType::FixedSizeList { element, .. } => {
            imports.push("ListBuilder".into());
            collect_builder_imports(&element.arrow_type, imports);
        }
        ArrowType::Struct { fields } => {
            imports.push("StructBuilder".into());
            for f in fields {
                collect_builder_imports(&f.arrow_type, imports);
            }
        }
        _ => {
            let info = type_mapping::rust_type_info(ty);
            imports.push(info.builder_type);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use arrowc_schema::arrow_type::{ArrowType, TimeUnit};
    use arrowc_schema::schema_def::ArrowFieldDef;
    use std::collections::BTreeMap;

    #[test]
    fn test_generate_full_rust_file() {
        // Arrange
        let schema = ArrowSchemaDef {
            name: "UserEvents".into(),
            fields: vec![
                ArrowFieldDef::new("user_id", ArrowType::Utf8).with_nullable(false),
                ArrowFieldDef::new("age", ArrowType::Int32),
                ArrowFieldDef::new("score", ArrowType::Float64),
                ArrowFieldDef::new(
                    "event_time",
                    ArrowType::Timestamp {
                        unit: TimeUnit::Microsecond,
                        timezone: Some("UTC".into()),
                    },
                ),
                ArrowFieldDef::new(
                    "tags",
                    ArrowType::List {
                        element: Box::new(ArrowFieldDef::new("item", ArrowType::Utf8)),
                    },
                ),
            ],
            metadata: BTreeMap::new(),
        };

        // Act
        let output = generate_rust_file(&schema);

        // Assert
        assert!(output.contains("// Generated by arrowc. Do not edit."));
        assert!(output.contains("use arrow::datatypes::{DataType, Field, Schema, TimeUnit}"));
        assert!(output.contains("pub struct UserEventsSchema;"));
        assert!(output.contains("pub struct UserEventsBuilder"));
        assert!(output.contains("pub struct UserEventsReader<'a>"));
        assert!(output.contains("pub fn schema() -> Schema"));
        assert!(output.contains("pub fn append(&mut self"));
        assert!(output.contains("pub fn try_new(batch: &'a RecordBatch)"));
    }

    #[test]
    fn test_generate_file_with_struct_companion() {
        // Arrange
        let schema = ArrowSchemaDef {
            name: "Order".into(),
            fields: vec![
                ArrowFieldDef::new("id", ArrowType::Int64).with_nullable(false),
                ArrowFieldDef::new(
                    "items",
                    ArrowType::List {
                        element: Box::new(ArrowFieldDef::new(
                            "item",
                            ArrowType::Struct {
                                fields: vec![
                                    ArrowFieldDef::new("name", ArrowType::Utf8),
                                    ArrowFieldDef::new("qty", ArrowType::Int32),
                                ],
                            },
                        )),
                    },
                ),
            ],
            metadata: BTreeMap::new(),
        };

        // Act
        let output = generate_rust_file(&schema);

        // Assert
        assert!(
            output.contains("pub struct OrderItems<'a>"),
            "missing companion struct in:\n{output}"
        );
        assert!(
            output.contains("pub name: Option<&'a str>"),
            "missing name field in:\n{output}"
        );
        assert!(
            output.contains("pub qty: Option<i32>"),
            "missing qty field in:\n{output}"
        );
        assert!(
            output.contains("items: Option<&[OrderItems<'_>]>"),
            "missing typed append param in:\n{output}"
        );
        assert!(
            output.contains("for row in rows"),
            "missing row iteration in:\n{output}"
        );
    }
}
